-- 04 - Service quality analysis | SQL Server / T-SQL
-- 0 is retained as a distinct survey code. A second rated-only ranking excludes 0.
WITH service_gaps AS (
 SELECT 'Inflight WiFi' service_name,AVG(CASE WHEN satisfaction='True' THEN CAST(Inflight_wifi_service AS FLOAT) END) satisfied_avg,AVG(CASE WHEN satisfaction<>'True' THEN CAST(Inflight_wifi_service AS FLOAT) END) dissatisfied_avg FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Departure/Arrival Time Convenience',AVG(CASE WHEN satisfaction='True' THEN CAST(Departure_Arrival_time_convenient AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' THEN CAST(Departure_Arrival_time_convenient AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Ease of Online Booking',AVG(CASE WHEN satisfaction='True' THEN CAST(Ease_of_Online_booking AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' THEN CAST(Ease_of_Online_booking AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Gate Location',AVG(CASE WHEN satisfaction='True' THEN CAST(Gate_location AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' THEN CAST(Gate_location AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Food and Drink',AVG(CASE WHEN satisfaction='True' THEN CAST(Food_and_drink AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' THEN CAST(Food_and_drink AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Online Boarding',AVG(CASE WHEN satisfaction='True' THEN CAST(Online_boarding AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' THEN CAST(Online_boarding AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Seat Comfort',AVG(CASE WHEN satisfaction='True' THEN CAST(Seat_comfort AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' THEN CAST(Seat_comfort AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Inflight Entertainment',AVG(CASE WHEN satisfaction='True' THEN CAST(Inflight_entertainment AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' THEN CAST(Inflight_entertainment AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'On-board Service',AVG(CASE WHEN satisfaction='True' THEN CAST(On_board_service AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' THEN CAST(On_board_service AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Leg Room Service',AVG(CASE WHEN satisfaction='True' THEN CAST(Leg_room_service AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' THEN CAST(Leg_room_service AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Baggage Handling',AVG(CASE WHEN satisfaction='True' THEN CAST(Baggage_handling AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' THEN CAST(Baggage_handling AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Check-in Service',AVG(CASE WHEN satisfaction='True' THEN CAST(Checkin_service AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' THEN CAST(Checkin_service AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Cleanliness',AVG(CASE WHEN satisfaction='True' THEN CAST(Cleanliness AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' THEN CAST(Cleanliness AS FLOAT) END) FROM dbo.airline_satisfaction)
SELECT service_name,CAST(satisfied_avg AS DECIMAL(6,3)) satisfied_avg,CAST(dissatisfied_avg AS DECIMAL(6,3)) dissatisfied_avg,CAST(satisfied_avg-dissatisfied_avg AS DECIMAL(6,3)) rating_gap
FROM service_gaps ORDER BY rating_gap DESC;

WITH service_gaps AS (
 SELECT 'Inflight WiFi' service_name,AVG(CASE WHEN satisfaction='True' AND Inflight_wifi_service>0 THEN CAST(Inflight_wifi_service AS FLOAT) END) satisfied_avg,AVG(CASE WHEN satisfaction<>'True' AND Inflight_wifi_service>0 THEN CAST(Inflight_wifi_service AS FLOAT) END) dissatisfied_avg FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Departure/Arrival Time Convenience',AVG(CASE WHEN satisfaction='True' AND Departure_Arrival_time_convenient>0 THEN CAST(Departure_Arrival_time_convenient AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' AND Departure_Arrival_time_convenient>0 THEN CAST(Departure_Arrival_time_convenient AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Ease of Online Booking',AVG(CASE WHEN satisfaction='True' AND Ease_of_Online_booking>0 THEN CAST(Ease_of_Online_booking AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' AND Ease_of_Online_booking>0 THEN CAST(Ease_of_Online_booking AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Gate Location',AVG(CASE WHEN satisfaction='True' AND Gate_location>0 THEN CAST(Gate_location AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' AND Gate_location>0 THEN CAST(Gate_location AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Food and Drink',AVG(CASE WHEN satisfaction='True' AND Food_and_drink>0 THEN CAST(Food_and_drink AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' AND Food_and_drink>0 THEN CAST(Food_and_drink AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Online Boarding',AVG(CASE WHEN satisfaction='True' AND Online_boarding>0 THEN CAST(Online_boarding AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' AND Online_boarding>0 THEN CAST(Online_boarding AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Seat Comfort',AVG(CASE WHEN satisfaction='True' AND Seat_comfort>0 THEN CAST(Seat_comfort AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' AND Seat_comfort>0 THEN CAST(Seat_comfort AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Inflight Entertainment',AVG(CASE WHEN satisfaction='True' AND Inflight_entertainment>0 THEN CAST(Inflight_entertainment AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' AND Inflight_entertainment>0 THEN CAST(Inflight_entertainment AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'On-board Service',AVG(CASE WHEN satisfaction='True' AND On_board_service>0 THEN CAST(On_board_service AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' AND On_board_service>0 THEN CAST(On_board_service AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Leg Room Service',AVG(CASE WHEN satisfaction='True' AND Leg_room_service>0 THEN CAST(Leg_room_service AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' AND Leg_room_service>0 THEN CAST(Leg_room_service AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Baggage Handling',AVG(CASE WHEN satisfaction='True' AND Baggage_handling>0 THEN CAST(Baggage_handling AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' AND Baggage_handling>0 THEN CAST(Baggage_handling AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Check-in Service',AVG(CASE WHEN satisfaction='True' AND Checkin_service>0 THEN CAST(Checkin_service AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' AND Checkin_service>0 THEN CAST(Checkin_service AS FLOAT) END) FROM dbo.airline_satisfaction
 UNION ALL SELECT 'Cleanliness',AVG(CASE WHEN satisfaction='True' AND Cleanliness>0 THEN CAST(Cleanliness AS FLOAT) END),AVG(CASE WHEN satisfaction<>'True' AND Cleanliness>0 THEN CAST(Cleanliness AS FLOAT) END) FROM dbo.airline_satisfaction)
SELECT service_name,CAST(satisfied_avg AS DECIMAL(6,3)) satisfied_avg,CAST(dissatisfied_avg AS DECIMAL(6,3)) dissatisfied_avg,CAST(satisfied_avg-dissatisfied_avg AS DECIMAL(6,3)) rating_gap
FROM service_gaps ORDER BY rating_gap DESC;
